### ISSUE TITLE
Installation 0.3.5

### ISSUE THREAD

**Issue by logopolop** [Grafikart/grafisearch#11]
Depuis le nouveau tag, je ne peux plus lancer grafisearch sur mon poste.

Avant, il me suffisait de lancer la commande "./grafisearch" mais depuis cela m'affiche "exec format error: ./grafisearch"

J'ai bien la bonne version pour ma machine (MacOS processeur Intel) et la bonne version de Go d'installé.

J'ai essayé avec le code source et le Makefile, mais rien n'y fait, il me répond : "make: *** No rule to make target `install'.  Stop."

Je ne souhaite pas repasser au tag 0.3.4.. Il y aurait-il une solution ou alors je ne fais pas les bonnes étapes ?

Merci !

**Comment by logopolop** [comment]
Après vérification il semblerait que l'éxecutable MacOS soit pour ... windows ?

![Capture d’écran 2022-10-10 à 15 47 38](https://user-images.githubusercontent.com/17913029/194881249-f4a78525-ea33-4575-9bbe-d3ea232ce271.png)

**Comment by logopolop** [comment]
En passant par le code source et le MakeFile, j'ai pu faire l'installation, je vais faire une PR pour soumettre la correction de l'anomalie que j'ai rencontré

**Comment by magiceupho** [comment]
Bonjour,
@logopolop Quelle est la solution pour installer et lancer l'application svp ?
J'ai ```exec format error: ./grafisearch``` au lancement dans le terminal.
Merci d'avance
